version: 2.1

orbs:
  slack: circleci/slack@4.9.3

jobs:
  build:
    docker:
      - image: maven:3.8.1-jdk-11
      - image: cimg/base:2022.09
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and test Maven project
          command: mvn clean install
      - run:
          name: Build Docker image
          command: |
            apt-get update
            apt-get install -y docker.io
            DOCKER_IMAGE=appcicd
            docker build -t $DOCKER_IMAGE .
            docker images
            IMAGE_ID=$(docker images -q $DOCKER_IMAGE)
            echo "Built Docker image ID: $IMAGE_ID with tag: $DOCKER_IMAGE"
            echo "export DOCKER_IMAGE=$DOCKER_IMAGE" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Tag and Push Docker image to Docker Hub
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker tag $DOCKER_IMAGE $DOCKERHUB_USERNAME/$DOCKER_IMAGE:$TAG
            docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE:$TAG
      - run:
          name: Update Kubernetes Deployment with New Image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            sed -i "s|fluencedevops.jfrog.io/fluence-repo/appcicd:.*|fluencedevops.jfrog.io/fluence-repo/appcicd:$TAG|g" k8s/deployment.yaml
            cat k8s/deployment.yaml
      - run:
          name: Apply Kubernetes Manifests
          command: |
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml
      - run:
          name: Trigger ArgoCD Sync
          command: |
            argocd app sync fluence-deployment --auth-token $ARGOCD_AUTH_TOKEN


workflows:
  version: 2
  send-notification:
    jobs:
      - build
      - notify_slack:
          requires:
            - build
