version: 2.1

orbs:
  slack: circleci/slack@4.9.3

jobs:
  build:
    docker:
      - image: maven:3.8.1-jdk-11
      - image: cimg/base:2022.09
        auth:
          username: 1201abhi
          password: dockerhub1201
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and test Maven project
          command: mvn clean install
      - run:
          name: Build Docker image
          command: |
            apt-get update
            apt-get install -y docker.io
            DOCKER_IMAGE=appcicd
            docker build -t $DOCKER_IMAGE .
            docker images
            IMAGE_ID=$(docker images -q $DOCKER_IMAGE)
            echo "Built Docker image ID: $IMAGE_ID with tag: $DOCKER_IMAGE"
            echo "export DOCKER_IMAGE=$DOCKER_IMAGE" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Tag and Push Docker image to Docker Hub
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker tag $DOCKER_IMAGE 1201abhi/$DOCKER_IMAGE:$TAG
            docker push 1201abhi/$DOCKER_IMAGE:$TAG

  notify_slack:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  version: 2
  send-notification:
    jobs:
      - build
      - notify_slack:
          requires:
            - build
